# Generated by Django 2.0.7 on 2020-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='SSN',
            new_name='ssn',
        ),
    ]
