# Generated by Django 2.0.7 on 2020-10-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201027_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Is_IT',
            new_name='is_it',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='VoteHistory',
            new_name='vote_history',
        ),
    ]
