# Generated by Django 2.0.7 on 2020-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201027_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ssn',
            field=models.CharField(max_length=255),
        ),
    ]
